USE mysql

CREATE DATABASE IF NOT EXISTS WORDPRESS_TITLE;
CREATE USER IF NOT EXISTS 'WORDPRESS_USER_LOGIN'@'%' IDENTIFIED BY 'WORDPRESS_USER_PASSWORD';
GRANT ALL PRIVILEGES ON WORDPRESS_USER_LOGIN. * TO 'WORDPRESS_USER_LOGIN'@'%';

FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'WORDPRESS_ADMIN_PASSWORD';