CREATE DATABASE ${WORDPRESS_DB_DATABASE};


CREATE USER ${WORDPRESS_USER_LOGIN}@'%' IDENTIFIED BY ${WORDPRESS_USER_PASSWORD};


GRANT ALL PRIVILEGES ON ${WORDPRESS_DB_DATABASE}.* TO ${WORDPRESS_USER_LOGIN}@'%' IDENTIFIED BY ${WORDPRESS_USER_PASSWORD};


FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY ${WORDPRESS_ROOT_PASSWORD};

FLUSH PRIVILEGES;