version: '3'

services:
  nginx:
    build: ./services/nginx
    ports: 
      - "443:443"
    restart: always
    volumes:
      # - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - wp_data:/var/www/html
    networks:
      - network_inception
    depends_on:
      - wordpress
  wordpress:
    build: ./services/wordpress_php
    depends_on:
      - mariadb
    restart: always
    # ports:
    #   - "9000:9000"
    volumes:
      - wp_data:/var/www/html
    env_file:
      - ./.env
    networks:
      - network_inception
  mariadb:
    build: ./services/mariaDB
    restart: always
    volumes:
      - mariadb_data:/var/lib/db
    # ports:
    #   - "3307:3306"
    env_file:
      - ./.env
volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/db
      o: bind
networks:
  network_inception:
    driver: bridge