version: '3'

services:
  nginx:
    build: ./services/nginx
    ports: 
      - "443:443"
    restart: always


  wordpress:
    build: ./services/wordpress
    depends_on:
      - mariaDB
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    environment:
      - .env

  mariaDB:
    build: ./services/mariaDB
    restart: always
    volumes:
      - mariaDB_data:/var/lib/mysql
    environment:
      - .env

  volumes:
    wp_data:
    mariaDB_data: